### ISSUE TITLE
module is not callable

### ISSUE THREAD

**Issue by AhmadShaik** [primetang/LSD-OpenCV-MATLAB#5]
I am trying to execute a example script, but I am getting error "module is not callable"
`runfile('/data/Work/workspace/seperator-detection/cap-python-lsd/pylsd/example/example_cv2.py')
Traceback (most recent call last):

  File "<ipython-input-4-5edd2cbe5322>", line 1, in <module>
    runfile('/data/Work/workspace/seperator-detection/cap-python-lsd/pylsd/example/example_cv2.py')

  File "/data/repos/tfenv/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/data/repos/tfenv/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/data/Work/workspace/seperator-detection/cap-python-lsd/pylsd/example/example_cv2.py", line 16, in <module>
    lines = lsd(gray)

TypeError: 'module' object is not callable`

**Comment by Fansgithub2019** [comment]
I have the same problem, did you solve it?

**Comment by Fansgithub2019** [comment]
Here lsd points to C: \...\pylsd-0.0.1-py3.8.egg \ pylsd \ lsd.py file, this is a module, I actually want to call the lsd function defined in it, so change it to lines = lsd. lsd (gray)
