### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by chiboreache** [primetang/LSD-OpenCV-MATLAB#6]
```python
Traceback (most recent call last):
  File "/home/userbest/Work/ocv-python/6_LSD.py", line 4, in <module>
    from pylsd import lsd
  File "/usr/lib/python3.7/site-packages/pylsd/__init__.py", line 8, in <module>
    from lsd import lsd
ModuleNotFoundError: No module named 'lsd'
```

**Comment by HackNet1997** [comment]
Same issue

**Comment by wangkai326** [comment]
same issue

**Comment by wangkai326** [comment]
> ```python
> Traceback (most recent call last):
>   File "/home/userbest/Work/ocv-python/6_LSD.py", line 4, in <module>
>     from pylsd import lsd
>   File "/usr/lib/python3.7/site-packages/pylsd/__init__.py", line 8, in <module>
>     from lsd import lsd
> ModuleNotFoundError: No module named 'lsd'
> ```



> ``
> from pylsd.bindings.lsd_ctypes import *

**Comment by ixtiyoruz** [comment]
install it from source the issue was fixed

**Comment by shreyas23** [comment]
Or if you installed it through pip in my case: change all the imports to relative imports. 

Ex. from `from lsd import lsd` to `from .lsd import lsd` and same for the module errors for the bindings afterwards.

**Comment by hpc203** [comment]
pip install ocrd-fork-pylsd==0.0.3
from pylsd.lsd import lsd

**Comment by konsnos** [comment]
> pip install ocrd-fork-pylsd==0.0.3 from pylsd.lsd import lsd

I've updated the version to 0.0.8 and it worked.
